# Generated by Django 2.1.1 on 2018-12-14 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0008_auto_20181214_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='masthead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
