# Generated by Django 2.1.1 on 2018-12-14 11:05

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_formpage_masthead'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
